services:
    db:
        container_name: db-granja
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: db
            POSTGRES_USER: db
            POSTGRES_DB: granja
        volumes:
            - db_granja:/var/lib/postgresql/data
        ports:
            - 5432:5432
        extra_hosts:
            - "host.docker.internal:host-gateway"

    
    web:
        container_name: web-granja
        image: web-granja
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./backend:/code
        ports:
            - 8000:8000
        env_file:
            - ./.env
        depends_on:
            - db   
        extra_hosts:
            - "host.docker.internal:host-gateway"
    

volumes:
    db_granja:
