import type { Metadata } from "next";
import { Inter, Heebo, Roboto } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import "../styles/index.scss";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";

const heebo = localFont({
  src: "./fonts/Heebo.ttf",
  variable: '--heebo'
});
const roboto = localFont({
  src: "./fonts/RedHat.ttf",
  variable: '--roboto'
});

export const metadata: Metadata = {
  title: "Sistema De Gestion De Agricultura",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
        "min-h-screen bg-gray-100 flex w-full",
        heebo.variable,
        roboto.variable
      )}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
